### ISSUE TITLE
Updating to 1.0.1 broke IE

### ISSUE THREAD

**Issue by daisy1754** [bigcommerce/request-sender-js#25]
Hi BigCommerce team, 

We recently updated this library from 0.5.1 to 1.0.1, and for some reason it broke IE. It seems like somehow arrow function (that is not supported by IE) is included in our bundle but I couldn't pinpoint where it was coming from. Do you have any idea how it happened? Also do you have any policy around what browsers to support?

![arrow_function](https://user-images.githubusercontent.com/980077/81723255-74170800-9437-11ea-8f00-a9488a67fdf2.png)

**Comment by chanceaclark** [comment]
Hey @daisy1754, I'll take a look at this.

**Comment by chanceaclark** [comment]
@daisy1754 here's an update on my findings.

We actually compile all of our files [down to es5](https://github.com/bigcommerce/request-sender-js/blob/master/tsconfig.json#L22).

I noticed from your screenshot that code is from the `query-string` lib. In [version `6.x.x`](https://github.com/sindresorhus/query-string/releases/tag/v6.0.0), they got rid of older browser support. If we need to support older browsers then we can bump `query-string` down to `5.x.x`, otherwise your build process can (and IMO should) be the one transpiling any modules getting imported.

I'm still having some internal discussions on whether or not we should bump the version down. In the meantime I would take a look to see if you can modify your build. I'll keep you posted.

**Comment by chanceaclark** [comment]
Fixed in `1.0.2`. @daisy1754 let me know if you run into any other issues.

**Comment by daisy1754** [comment]
awesome, thanks for quick turn around! 

for transpiling, I believe we only transpile our code but not node_modules, I'll check internally on why but for now I'll try 1.0.2 first. Really appreciate your help.
